### ISSUE TITLE
Possible to calculate a time difference?

### ISSUE THREAD

**Issue by Reached** [phoenixwong/vue2-timepicker#1]
Hi Phoenixwong,

I just had a quick look at the documentation, it looks really cool so far, but I was wondering if it's possible to calculate the time difference between two time-inputs?

e.g:

**Input 1:**

15:15

**Input 2:** 

17:30

**Time difference:**

2 hours and 15 minutes

**Comment by phoenixwong** [comment]
Hi @Reached ,

Thank you for asking. For time difference calculation, I recommend using [MomentJS](http://momentjs.com).

I created a pretty rough sample in jsFiddle: https://jsfiddle.net/fL1e086g/

For more detail information, please check the [official Docs here](http://momentjs.com/docs/#/displaying/difference/)

**Comment by Reached** [comment]
Hi @phoenixwong,

Thanks for the example, it's really helpful :)!

**Comment by phoenixwong** [comment]
Glad that it helps :)
