### ISSUE TITLE
How i can use it via cdn?

### ISSUE THREAD

**Issue by nvdfxx** [phoenixwong/vue2-timepicker#103]

**Comment by phoenixwong** [comment]
You can give [https://unpkg.com/](https://unpkg.com/) a try.

```
unpkg.com/:package@:version/:file
```

Take the latest version today (v1.0.8) for example --

- JS in UMD format: https://unpkg.com/vue2-timepicker@1.0.8/dist/VueTimepicker.umd.min.js
- CSS: https://unpkg.com/vue2-timepicker@1.0.8/dist/VueTimepicker.css

**Comment by zarpio** [comment]
Can you please share full example code, thanks.
I tried various ways but I am still unable to use it.

```
<link href="https://unpkg.com/vue2-timepicker@1.0.8/dist/VueTimepicker.css" rel="stylesheet" type="text/css" />
<script src="<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>" type="text/javascript"></script>
<script src="https://unpkg.com/vue2-timepicker@1.0.8/dist/VueTimepicker.umd.min.js"></script>

//import VueTimepicker from 'vue2-timepicker'
new Vue({
    el: '#app',
    // components: {
    //     vue-timepicker: window['vue2-timepicker']
    // },
    components: { VueTimepicker: window['vue2-timepicker'] },
    data: {
    }
});
```

**Comment by phoenixwong** [comment]
Hi @zarpio, I replied in your [main thread](https://github.com/phoenixwong/vue2-timepicker/issues/123#issuecomment-647101115)
