### ISSUE TITLE
This is not accessible in the browser

### ISSUE THREAD

**Issue by NiharRan** [phoenixwong/vue2-timepicker#104]
I try to use vue2-timepicker in the browser, but i couldn't.

**Comment by phoenixwong** [comment]
Can you provide more detailed information? It would be best if you can provide a working case, or reproduce the issue through JSFiddle or CodePen.

FYI, here is a [Vue2 Timepicker v1.0.8 Demo Base](https://jsfiddle.net/phoenixwong/fxbgu9Lz/) on JSFiddle. Please feel free to fork it as a scaffold.

Supplemental info like the Operating System, Browser Name, and Browser Version you used is also helpful.

**Comment by phoenixwong** [comment]
Closing this for lacking of information.
