### ISSUE TITLE
Allow format string to eliminate hours

### ISSUE THREAD

**Issue by wsitch** [phoenixwong/vue2-timepicker#108]
I'd like to use the vue2-timepicker for running pace times, which means I need a minute and second selector, no hours. 

However if I use format="mm:ss", the dropdown shows HH | mm | ss, but as requested the selected time is shown in the input field in "mm:ss" format.

Is it possible to eliminate the HH column in the dropdown selector when the format doesn't include hours?

**Comment by phoenixwong** [comment]
Hi @wsitch,

Thanks for providing a detailed use case. There was a duplicate feature request (#21), but it lacks example usage, so I closed that. Now it comes with a specific scenario. I'll add it to the roadmap soon.

In the meantime, you can try hiding the "hours" column with pure CSS. I made a quick [JSFiddle demo here](https://jsfiddle.net/phoenixwong/s09htvez/).

In short:

```html
<vue-timepicker class="my-timepicker" format="mm:ss"></vue-timepicker>
```

```css
.my-timepicker .select-list ul.hours {
  display: none;
}
```
