### ISSUE TITLE
Instant feedback after manual number input

### ISSUE THREAD

**Issue by jost-s** [phoenixwong/vue2-timepicker#113]
The manual input is a welcome addition. By default there's a delay of 500 ms after a number key is pressed.

My suggestion is to instantly reflect the pressed key and wait for another key to be pressed with a configurable timeout. I've submitted a PR for this change.

**Comment by AmitJoki** [comment]
When will the next release be?

**Comment by phoenixwong** [comment]
ETA: by next Monday.

**Comment by phoenixwong** [comment]
Hi guys, the enhancements released in _v1.1.1_.

FYI, I renamed the configurable timeout property to `manual-input-timeout`.
