### ISSUE TITLE
Is my HTML right?

### ISSUE THREAD

**Issue by OksXen** [phoenixwong/vue2-timepicker#114]
@phoenixwong  Am I doing something wrong here?
I can't get the VueTimePicker to display. 

I get this error message in the Console: 

> vue.js:634 [Vue warn]: Failed to mount component: template or render function not defined.
> found in
> ---> `<VueTimepicker>`
>      `<Root>`

`<html>`
`    <head>`
 `       <link rel="stylesheet" href="./VueTimepicker.css">`
 `   </head>`
`<body>`

`<div id="app">`
`    <vue-timepicker></vue-timepicker>`
`    <div>`
`        {{ message }}`
 `   </div>`
`</div>`

`<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>`
`<script src="./VueTimepicker.umd.js"></script>`

`<script>`
`   Vue.use(window.VueTimepicker);`

 `   var app = new Vue({`
`        data:{`
`            message: 'hello'`
`        },`
`       el: '#app',`
`        components:{ VueTimepicker}`
`   });`

`</script>`

`</body>`
`</html>`

**Comment by phoenixwong** [comment]
Hi @OksXen, 

I'm not sure whether we still need the `Vue.use(...)` in your case. But the `components` part doesn't seem correct at a glance. 

FYI, you can take a look at the [JSFiddle Demo (v.1.1.0) here](https://jsfiddle.net/phoenixwong/p1o4m7ae/). It uses a `<script>` block to import the UMD format JS as you do.

In short, the **components** part should be:

```javascript
new Vue({
  el: '#app',
  components:{
   // NOTE the ".default" here
    VueTimepicker: VueTimepicker.default
  },
  ...
});
```

**Comment by OksXen** [comment]
Hi @phoenixwong , 

Thank you. It's working now.
I wasn't sure if it was the way I implemented it, or if it were the documentation I followed. But anyhow, I appreciate it. 

Regards,
OksXen
