### ISSUE TITLE
How to handle its css for options? 

### ISSUE THREAD

**Issue by hanzlahabib** [phoenixwong/vue2-timepicker#122]
There are cases where things get hidden under something i want to manage it with z-index, what is flexible way for managing that?

**Comment by phoenixwong** [comment]
Hi @hanzlahabib,

Can you provide a more detailed example? Like which component's z-index you want to manage?

A JSFiddle or Codepen demo will be the best. Here is a [JSFiddle Demo Base (v1.1.3)](https://jsfiddle.net/phoenixwong/p1o4m7ae/), you can fork it as a scaffold.

Screenshots with clear notes will also do.

**Comment by phoenixwong** [comment]
I am closing this for lacking information. Please feel free to reopen it with a working demo.
