### ISSUE TITLE
Disabled timepicker not display value on safari

### ISSUE THREAD

**Issue by godshades** [phoenixwong/vue2-timepicker#124]
Hi, on chrome when disable it display gray color like this 
![image](https://user-images.githubusercontent.com/12244851/85534498-95c0fd00-b63b-11ea-985b-1f8c67dd24da.png)

But on safari, this color is white => can't see (maybe safari bug)

I need change style to this
```
.vue__time-picker input.display-time:disabled, .vue__time-picker input.display-time.disabled {
    color: gray !important;
}
```

**Comment by phoenixwong** [comment]
Hi @godshades,

Thanks for the report. However, I cannot reproduce it with the Safari on my end -- Version 13.1 (15609.1.20.111.8).

<img width="1370" alt="Safari-disabled-value-color-test" src="https://user-images.githubusercontent.com/6954306/85594261-59f95800-b67a-11ea-828b-6befe4938395.png">

Can you try opening [this JSFiddle](https://jsfiddle.net/phoenixwong/cfg2m5wn/) with your Safari and capture a screenshot? Along with your current Safari and macOS version will be even better.
