### ISSUE TITLE
Style input

### ISSUE THREAD

**Issue by DanFulcher** [phoenixwong/vue2-timepicker#127]
Is it possible to style the time picker input?

I've added a custom class, but the styles seem to be getting ignored.

**Comment by phoenixwong** [comment]
You can either add `!important` to force apply any CSS properties or use a higher priority CSS selector for the target `<input />`.

Check [JSFiddle Sample here](https://jsfiddle.net/phoenixwong/nh6jk0ma/).

---

Duplicates of #77
