### ISSUE TITLE
Feature Request: Should be able to use it as a directive.

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [phoenixwong/vue2-timepicker#128]
If we can use it as a directive on any element that would be really great. For example i am using vuetify along with vue.js. In my form all form input elements has some king of stylings provided by vuetify. But when i use this vue2-timepicker i am loosing all the css and floating labels.

`Before entering input values`
<img width="781" alt="Screenshot 2020-08-14 at 10 47 42 PM" src="https://user-images.githubusercontent.com/9896335/90275601-2e2b6f00-de80-11ea-97fc-a5467b98d3cf.png">

`After entering input values`
<img width="793" alt="Screenshot 2020-08-14 at 10 47 32 PM" src="https://user-images.githubusercontent.com/9896335/90275604-308dc900-de80-11ea-9fb4-3209ce661a91.png">

In the above image i don't know to which label the time belongs to as the floating lable is missing.

I managed to add some css to look like the same vuetify form input element, but the floating label is not working as expected.

**Comment by phoenixwong** [comment]
> If we can use it as a directive on any element that would be really great.

By referring "directive", If what you meant was the [Vue custom directive](https://vuejs.org/v2/guide/custom-directive.html), the answer is "Nope". This repository is not built for that in the first place. We welcome any potential contributors to fork and help.

Besides, from the screenshot you provided, it seems more like a CSS issue, and/or value reactive issue. Changing VueTimepicker to a directive is not going to resolve the problem.

It would great if you can provide a live demo similar to the case you made in the screenshot. Here's a [demo base with the latest Vue Timepicker in JSFiddle](https://jsfiddle.net/phoenixwong/p1o4m7ae/). Please feel free to fork it as a scaffold.

**Comment by phoenixwong** [comment]
I am closing this for lacking information. Please feel free to reopen it with a demo, with which we can do further investigation.
