### ISSUE TITLE
Change disabled attribute.

### ISSUE THREAD

**Issue by yakyn0103** [phoenixwong/vue2-timepicker#130]
How can i change the attribute dynamically. 
Thanks.

**Comment by phoenixwong** [comment]
Set a _Boolean_ variable to control the `disabled` state, and change its value when you needed to.

```javascript
{
  data () {
    return {
      toDisabled: false
    }
  }
}
```

```html
<vue-timepicker :disabled="toDisabled"></vue-timepicker>
```

[Documentation: Disable Picker](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#disable-picker)
