### ISSUE TITLE
manual-input shouldn't be invalid because of mismatch with intervals

### ISSUE THREAD

**Issue by tomasvanrijsse** [phoenixwong/vue2-timepicker#131]
I've setup vue-timepicker like this:
```
<vue-timepicker :minute-interval="15" manual-input />
```
My intention was to give the user a generic text input with an input mask.
I've kept the dropdown just as a bonus but narrowed down the options to make it easier to use.

When a user types in `18:11` the timepicker will turn red because `18:11` doesn't match the 15 minute interval.
I'd like to disable that validation, the dropdown options only serve as a UX feature not as validation.

**Comment by phoenixwong** [comment]
By adding "skip-error-style" to `input-class`, you can mute the red border style for invalid state.

```html
<timepicker input-class="skip-error-style"></timepicker>
```

Here's the documentation for [Helper Classes](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#helper-css-class-names).
