### ISSUE TITLE
manual-input and active option scroll into view

### ISSUE THREAD

**Issue by tomasvanrijsse** [phoenixwong/vue2-timepicker#132]
I've used `manual-input` on my vue-timepicker instances.
When a user types in the value, e.g. 08:45, he won't see the active state in the dropdown.
![image](https://user-images.githubusercontent.com/1403466/93346433-44886a00-f834-11ea-92d2-02e6c725f046.png)

It would be a nice enhancement if the active value would scroll into view.
In technical terms, something like this:
```
this.$el.querySelector('ul.hours li.active').scrollIntoView()
```

**Comment by phoenixwong** [comment]
The existing `auto-scroll` feature should do the trick ([Documentation here](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#auto-scroll)).
