### ISSUE TITLE
Feature Request: append-to-body

### ISSUE THREAD

**Issue by iomariani** [phoenixwong/vue2-timepicker#133]
Sometimes the component is wrapped into an container with overflow: hidden;

![image](https://user-images.githubusercontent.com/1733348/93415366-b6cf6d80-f879-11ea-9c43-e1c4fee0ab15.png)

That causes the dropdown list to be hidden on the container...
A append-to-body prop that would instead append the list to the body would be nice!

Similar to what vueSelect has https://vue-select.org/api/props.html#appendtobody, along with a function to calculate where the position will be as well...

**Comment by phoenixwong** [comment]
Thanks for the suggestion, @iomariani!

In the meantime, please give the brand new `drop-direction` feature a try -- It's release in the latest [v1.1.5](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v1.1.5). With this new feature, you can set make dropdown open above the input if needed.

**Comment by iomariani** [comment]
@phoenixwong it definitely does help in my case as well. Thank you!

**Comment by phoenixwong** [comment]
Feature released in **v1.1.6**.

Please be note that you may need to modify some CSS selector names if you have customized styles for the dropdown picker. E.g., a custom background color.

Please check the documentation [here](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#append-to-body) for more information.
