### ISSUE TITLE
More than 23 hours?

### ISSUE THREAD

**Issue by Avratz** [phoenixwong/vue2-timepicker#135]
Hello, I am currently using this awesome plugin and I have encounter with a problem. 
Can I set the picker with for example 30 hours or 100 hours? 
Is there any way of doing this?

Thank you very much.

**Comment by phoenixwong** [comment]
Hi @Avratz,

Vue2 Timepicker only supports [the time formats mentioned in the documentation](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#customized-time-format). Values `> 24` and `< 0` are out of the range. It's the core of this plugin, and most of the features depend on it. So I'm afraid we're not going to change the acceptable values in the foreseeable future.

Please feel free to fork this repo and adjust it to fit your requirements.
