### ISSUE TITLE
:hour-range usage

### ISSUE THREAD

**Issue by shrivasraghavan** [phoenixwong/vue2-timepicker#137]
Hello,
I have the mix and max range saved by the user from another form input. How do I use this in the hour-range?
I see :hour-range only takes numeric values and not variable names that hold values.

For example, if starttime and endtime hold the hour-range, how can I use it with vue-timepicker?

Thanks

**Comment by phoenixwong** [comment]
> I see :hour-range only takes numeric values and not variable names that hold values.

You can create a data variable, or a computed variable, and set it as the value for `:hour-range`

```javascript
data () {
  return {
    // Accepts value from other inputs
    startHour: 8,
    endHour: 17,
    ...
  }
},

computed: {
    myHourRange () {
      return [[this.startHour, this.endHour]]
    },
    ...
}
```

Then in the HTML template -- 

```html
<vue-timepicker :hour-range="myHourRange"></vue-timepicker>
```
