### ISSUE TITLE
manual-input flakey

### ISSUE THREAD

**Issue by kerbo** [phoenixwong/vue2-timepicker#141]
Using this config in your playground:

<vue-timepicker
  format="hh:mm A"
  manual-input
  hide-dropdown
  v-model="yourTimeValue">
</vue-timepicker>

Existing time is 01:04 AM

If I select minutes (both 0 and 4 highlighted) and type 3 -> value is 01:03 AM this is OK
If I type 4 -> value is 01:04 AM, not OK should be 01:34 AM

If I press 4 several times it will stick -> 01:34 AM

You can also select one digit (e.g., 0 of 04) and if typing 3 the minutes change to 03 - I would expect 34

I think when clicking on a hours or minutes or AM, the entire 2 digits should highlight, you shouldn't be able to select a single digit.

The manual input behavior of the Chrome implementation of <input type='time'/> works great. Might be worth looking at.

**Comment by phoenixwong** [comment]
That's the expected behavior of Manual Input Timeout explained in the Documentation [here](https://github.com/phoenixwong/vue2-timepicker#manual-input-timeout).

**Comment by kerbo** [comment]
There is no timeout value that makes this work logically. With the selection behavior, manual input is not usable.

**Comment by phoenixwong** [comment]
What's the issued browser name and version?

**Comment by kerbo** [comment]
Chrome 87.0.4280.141
