### ISSUE TITLE
Issue with Browserify

### ISSUE THREAD

**Issue by sagarshinde15april** [phoenixwong/vue2-timepicker#20]
Browserify is unable parse this library
Giving following error

>> <script>
>> ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. Use --force to continue.

Is support of this library available to browserify?

**Comment by phoenixwong** [comment]
Sorry for the long wait. Please try with the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) [#66] and feel free to reopen this ticket if the problem still exists.
