### ISSUE TITLE
Can I use this without hours?

### ISSUE THREAD

**Issue by sandervanhooft** [phoenixwong/vue2-timepicker#21]
I was unable to find this in the documentation / playground. Can I use this component without the hours? So with a `mm:ss` format?

**Comment by martinnaughton** [comment]
Yes create the object like this.
```
minute: { 
    'mm': ' ', 
     'ss': ' '
}

```

**Comment by martinnaughton** [comment]
and the format attribute  format="mm:ss"

**Comment by mirikerstein** [comment]
Hello,
I have the same question. What do you mean by "create the object" - where exactly? Which object? Thank you!

**Comment by Kasanomo** [comment]
It does not work for me. Did it work for you @sandervanhooft ?

**Comment by phoenixwong** [comment]
I'm a little bit undecided about this feature. Can anyone provide me an example of real-life usage? Like, in what situations you would like to cut-off the hour input.

**Comment by phoenixwong** [comment]
I decide to suspend this feature request since it lacks application scenarios.

For anyone who wants to vote for this feature, please provide me some use cases on this ticket. Thanks!
