### ISSUE TITLE
[Request] Disabled Option

### ISSUE THREAD

**Issue by xxRockOnxx** [phoenixwong/vue2-timepicker#22]
Would like to be able to set this as disabled.
I'll try to make a PR on this one.

Btw, my first thought was disabled input, but also having a disabled value is a good idea too.

**Comment by xxRockOnxx** [comment]
Made a PR for this option. Just go check it out for those who needs it.

**Comment by sergiocastrovale** [comment]
Even better would be to be able to enable/disable by trigger.

I'm coupling a datepicker with vue2-timepicker and it makes little sense for users to be able to pick the time frame _before_ picking any date.

**Comment by martinnaughton** [comment]
I second this request. I see that @xxRockOnxx  you have it in your forked repo. It would be handy to have it in the npm package @phoenixwong

**Comment by YamenSharaf** [comment]
Just FYI. I hope you don't mind, but I added this package to NPM for my need, feel free to use it

https://www.npmjs.com/package/vue2-timepicker-disabled

**Comment by dhiraj1site** [comment]
> Just FYI. I hope you don't mind, but I added this package to NPM for my need, feel free to use it
> 
> https://www.npmjs.com/package/vue2-timepicker-disabled

How does the disabledValues props works please, I could not get it to work. This is what I tried         disabledTimes: { hours: ['1,2'], minute: ['00,00'], apm: ['am', 'pm'] },
 getting Cannot read property 'indexOf' of undefined

**Comment by erickcg** [comment]
is this going to be merged at all?

**Comment by xxRockOnxx** [comment]
@erickcg just use my fork. it's on npm already.
