### ISSUE TITLE
Cannot set property 'VueTimepicker' of undefined

### ISSUE THREAD

**Issue by kavalcante** [phoenixwong/vue2-timepicker#24]
I add the dist files in my project. But console shows me this error.

After using Vue.use(), another errors shows:
`
Uncaught TypeError: Cannot read property 'installed' of undefined`

Any ideas?

**Comment by tengqingya** [comment]
i  met the  same question....

Uncaught TypeError: Cannot set property 'VueTimepicker' of undefined
    at vue2-timepicker.min.js:1
    at vue2-timepicker.min.js:1
(anonymous) @ vue2-timepicker.min.js:1
(anonymous) @ vue2-timepicker.min.js:1
vue.js:3747 Uncaught TypeError: Cannot read property 'installed' of undefined
    at Function.Vue.use (vue.js:3747)
    at HTMLDocument.<anonymous> (orignal2.js:2)
    at j (VM3551 common.js:2)

my code:
$(function () {
    Vue.use(window.VueTimepicker)
    new Vue({
        el: "#secondFram",
        data: {
            bookName:"a",
            isHot:-1,
            cpSite:-1
        },
        components: { VueTimepicker },
.....

**Comment by dominik-selmeci** [comment]
Hi, i have the same problem. It shows me error:
> Uncaught TypeError: Cannot read property 'installed' of undefined
> at Function.Vue.use (vue@2.3.0:4067)

I reproduced problem at [codepen](https://codepen.io/dominik_selmeci/pen/ybMaNw?editors=1010#0)

**Comment by getsetbro** [comment]
I got this error as well from the "min.js" file but not when I switched to the unminified file.

**Comment by SewonYun** [comment]
thank you @getsetbro , I solved it.

**Comment by phoenixwong** [comment]
Sorry for the long wait. Latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) fixes this issue now (#66)

Please give it a try and feel free to reopen this ticket if the problem still exists.
