### ISSUE TITLE
Is there supports for multiple datepicker?

### ISSUE THREAD

**Issue by Beomi** [phoenixwong/vue2-timepicker#25]
Does Vue2-timepicker supports multiple datepicker? 
I've couldn't find docs for this.

**Comment by xxRockOnxx** [comment]
```
<vue-timepicker></vue-timepicker>
<vue-timepicker></vue-timepicker>
```

how about that? Question is not very clear.

**Comment by Beomi** [comment]
Sorry for your confusion. 
I mean, is there any option for multiple date picker like this:
multidatespickr.sourceforge.net

**Comment by xxRockOnxx** [comment]
I looked at the site. What demo are you specifically looking at?
Btw, this project is not actively maintained anymore. I have a fork of this that I can improve if needed.

**Comment by Beomi** [comment]
[http://multidatespickr.sourceforge.net/#from--input-demo](http://multidatespickr.sourceforge.net/#from--input-demo)
Like above one. When I focus on input field, I'd like to show up date picker which supports multiple date selecting.

**Comment by xxRockOnxx** [comment]
No, there's no option like that. How about just a dynamic `vue-timepicker` ? Something like a button that says "Add more date"?

**Comment by phoenixwong** [comment]
Sorry for the late reply. I'd suggest using `v-for` paired with an Array or Object to handle your `<vue-timepicker>`s. The [`v-for` Sample](https://phoenixwong.github.io/vue2-timepicker/#vForSample)
