### ISSUE TITLE
Can we exclude values from the hours list?

### ISSUE THREAD

**Issue by sergiocastrovale** [phoenixwong/vue2-timepicker#26]
I'm building a reservations system and having the time picker start at midnight doesn't really make sense (nor do any hours between midnight and 9AM).

Is there any way we can customize that array of values?

**Comment by xxRockOnxx** [comment]
I have a fork that does exactly this. Consider trying it. I think this repo is dead already and I'm trying to maintain it as long as I could.

**Comment by sergiocastrovale** [comment]
Great! Silly question but ... how can I use a forked repo via NPM?

**Comment by sergiocastrovale** [comment]
Cool, I'll move on to your fork then. Maybe you should update the doc file with the new features, they are a real upgrade to the original picker and it might be hard for newcomers to understand it. Thanks!

**Comment by phoenixwong** [comment]
Duplicate of #63
