### ISSUE TITLE
v-model not updating

### ISSUE THREAD

**Issue by sergiocastrovale** [phoenixwong/vue2-timepicker#27]
Here's my code:

`<vue-timepicker v-model="newEventStartTime" format="HH:mm" :minute-interval="30" hide-clear-button></vue-timepicker>`

`
data: function() {
            return {
                newEventStartTime: { HH: '09', mm: '00', ss: '00' }
            }
        },
`

I'm watching the newEventStartTime object and whenever I click on a different time than the one initially set nothing changes. The UI shows the new timestamp, but I need to store it in newEventStartTime so I can append the timeframe to a date.

What am I doing wrong?

Paging @xxRockOnxx as he seems to be on top of the repo now.

**Comment by oranzhang** [comment]
Got same issue, and I've fixed it within my fork.

see https://github.com/oranzhang/vue2-timepicker

**Comment by oranzhang** [comment]
As @xxRockOnxx has refactored the project, it might be have fixed your issue though the refactored version is not published on NPM.
You can add it to your project by `yarn add https://github.com/xxRockOnxx/vue2-timepicker` or just use my dirty fix by `yarn add https://github.com/oranzhang/vue2-timepicker`

**Comment by richoid** [comment]
Same issue. Is there a simple fix?

**Comment by xxRockOnxx** [comment]
@richoid have you tried using my fork like @oranzhang had suggested?

**Comment by xxRockOnxx** [comment]
package.json is different but the main code is different. Can you give a simplest replication so I can try it and make a fix?

**Comment by phoenixwong** [comment]
Sorry for the long wait. Latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) fixes this issue now (#66)

Please give it a try and feel free to reopen this ticket if the problem still exists.

**Comment by xxRockOnxx** [comment]
@phoenixwong welcome back! Appreciate your work

**Comment by phoenixwong** [comment]
@xxRockOnxx Thanks for your great work again! : )

I will keep hunting down the rest issues in the following weeks. PRs and discussions are all welcomed.

**Comment by phoenixwong** [comment]
Some more fixes were done in the [latest release](https://github.com/phoenixwong/vue2-timepicker/releases/latest) (v0.2.2)

See workable [jsFiddle sample here](https://jsfiddle.net/phoenixwong/hj721ywx/) with the data and method @sergiocastrovale provided in the main ticket.
