### ISSUE TITLE
Picker closes after each click

### ISSUE THREAD

**Issue by MithrandirDK** [phoenixwong/vue2-timepicker#3]
I have two time pickers in the same component with HH and mm elements.

Showing the time picker is no problem and clicking in the input field opens the drop downs. No problems so far. BUT, clicking on e.g. hour updates the field (and model) and then the drop downs close and I need to re-click the field to set the minutes portion.

Is this a known issue with a known resolution?

Edit: I am using the time picker in a modal popup. Is it possible that the click events interfere? The modal doesn't close when selecting a time element - only the time picker dropdowns

**Comment by phoenixwong** [comment]
Hi @MithrandirDK ,

Thanks for the report. I think it might be related to the click event propagation when nested in a popup modal. I did a little patch and released a new version (v0.1.4). Please update to the latest package and see if it resolve the issue for you?

**Comment by MithrandirDK** [comment]
I am afraid, it did not change anything - I'll do some more testing and see if it is caused by the modal, otherwise it will have to be something else in my code triggering this.

**Comment by phoenixwong** [comment]
Hmm... maybe try adding `.stop` handler to other components if you can? Plus, sometimes the `z-index` of overlay masks (modal, picker, popover, etc) are suspicious too.

**Comment by rubencanovaca** [comment]
Using stopEventPropagation() is something that should be avoided as it breaks normal event flow in the DOM.

**Comment by phoenixwong** [comment]
Feature updated in [v0.2.1](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.1)

[More comments](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.1) in #38
