### ISSUE TITLE
require.js引用了js文件、vue中使用报错

### ISSUE THREAD

**Issue by allan2coder** [phoenixwong/vue2-timepicker#30]
require.js引用了js文件、vue中使用报错
这应该与require.js无关吧，如图：

![qq 20170519180011](https://cloud.githubusercontent.com/assets/14307551/26243352/23ac991c-3cbe-11e7-9cf1-8c6f8bc03aff.jpg)

![0v9 h 4upjqhemnw 37d5v](https://cloud.githubusercontent.com/assets/14307551/26243594/f753092c-3cbe-11e7-9f79-acaa107b7ff7.png)

**Comment by phoenixwong** [comment]
Sorry for the long wait. Latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) fixes this issue now. [#66]
