### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by c7pt7in** [phoenixwong/vue2-timepicker#34]
When I import `vue2-timepicker` like single file component
```
import VueTimepicker from 'vue2-timepicker'
```
I'm getting following webpack error
```
Uncaught Error: Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/var/www/gis/node_modules/vue2-timepicker/.babelrc" at 0, attempted to resolve relative to "/var/www/gis/node_modules/vue2-timepicker"
```
When I importing dist
```
import 'vue2-timepicker/dist/vue2-timepicker.min.css'
import VueTimepicker from 'vue2-timepicker/dist/vue2-timepicker.min.js'

Vue.use(VueTimepicker)
```
its works, but I'm getting error in console
```
[Vue warn]: Property or method "id" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

npm version 5.0.3, webpack version 2.2.1

**Comment by tomcoonen** [comment]
Same here using webpack.

**Comment by BartDeCaluwe** [comment]
+1

**Comment by tobischulz** [comment]
+1

**Comment by shroy** [comment]
After running into this [post](https://github.com/ratiw/vuetable-2/issues/41), I was able to solve the problem with the following installations..

`
  npm install babel-plugin-transform-runtime --save-dev
  npm install babel-preset-stage-2 --save-dev
  npm install babel-preset-es2015 --save-dev
`

**Comment by phoenixwong** [comment]
Sorry for the long wait. Please give the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) a try. [#66]

**Comment by phoenixwong** [comment]
Related to #15
