### ISSUE TITLE
ATTENTION: Before posting issues.

### ISSUE THREAD

**Issue by xxRockOnxx** [phoenixwong/vue2-timepicker#36]
I see that lots of people still uses this package but this repo is already dead at least based on my observations.

I forked this repo and refactored it and fixed the importable problem but that **doesn't** mean:

-  every problem is fixed though. You can submit PRs there and I can review it and approve it.
- I will solve every problem. I have other projects for living but I always check my Github.

**Comment by phoenixwong** [comment]
Thank you, @xxRockOnxx, for lending a helping hand! Sorry for the long silence. Dead repo rechanged in mid-2019 now 🔋
