### ISSUE TITLE
Picker stops propagation

### ISSUE THREAD

**Issue by c7pt7in** [phoenixwong/vue2-timepicker#38]
I have datepicker, and when I select date and click on timepicker, datepicker not closing because timepicker stops propagation.

I also have multiple timepickers in same component and everything works fine when I remove `.stop` from dist code. So, you should revert #3

**Comment by rubencanovaca** [comment]
Using stopEventPropagation() is something that should be avoided as it breaks normal event flow in the DOM.

**Comment by phoenixwong** [comment]
Enhancement released in [v0.2.1](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.1)

The `@click.stop` handler is only added to the dropdown picker now. Aimed to prevent the dropdown from closing on every value selection.

Click events will pass on the parent container in other circumstances.

For those who want to stop all click events propagation from `<vue-timepicker>`, please try

```html
<vue-timepicker @click.native.stop=""></vue-timepicker>
```
