### ISSUE TITLE
I try to import it but it doesn't work

### ISSUE THREAD

**Issue by hajarrashidi** [phoenixwong/vue2-timepicker#39]
Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\Users\\... \\node_modules\\vue2-timepicker"

**Comment by Muchwat** [comment]
me too

**Comment by levthedev** [comment]
I'm getting this issue as well

**Comment by stanislavweb** [comment]
+1

**Comment by sumitsingh366** [comment]
I am also facing this problem!

**Comment by paladosss** [comment]
Are you seriously? 
npm install --save-dev babel-preset-es2015

**Comment by atomdmac** [comment]
```npm install --save-dev babel-preset-es2015```
^^ This fixes the initial issue, though you'll be presented with a message encouraging you to use `babel-preset-env` instead.

**Comment by amitavroy** [comment]
Same error, even npm install --save-dev babel-preset-es2015 didn't help.

**Comment by xxRockOnxx** [comment]
Please see my fork for those having problems with import.

**Comment by phoenixwong** [comment]
Sorry for the long wait. Please give the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) a try. [#66]

**Comment by phoenixwong** [comment]
Related to #15
