### ISSUE TITLE
input name attribute for form submission

### ISSUE THREAD

**Issue by vortechron** [phoenixwong/vue2-timepicker#42]
input[class=display-time] element need to add name attribute for from submission.

**Comment by benedict-w** [comment]
+1

**Comment by phoenixwong** [comment]
Sorry for the long wait. Latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) fixes this issue now. (#66)(#62)

**Comment by vortechron** [comment]
@phoenixwong tq. u r the best
