### ISSUE TITLE
Change value programmatically doesn't changes display time

### ISSUE THREAD

**Issue by SDJeff** [phoenixwong/vue2-timepicker#44]
I have to boxes. If i change the first i add 3 hours to the second box. The value is correct but the display time doesn't update after the component is once created.

**Comment by xxRockOnxx** [comment]
have your tried looking at my fork? If my fork does not do what you want I might make some fix. Did some refactoring on it so it might work.

**Comment by shershen08** [comment]
I have similar question - in my case I want to be able to clear the value from the outside of the component. @xxRockOnxx does your fork https://github.com/xxRockOnxx/vue2-timepicker have a separate demo or list of added features ?

**Comment by xxRockOnxx** [comment]
The demo on my fork is based on the changes I made.

So far no added features because no one requested again yet.

I refactored it for like 70-80% I guess? So please try if it does not work just open an issue and I'll fix it.

**Comment by shershen08** [comment]
Great! I'll take a quick look asap. Coz I see the main repo is kind of not active any more

**Comment by shershen08** [comment]
I didn't see much changes in the demo https://xxrockonxx.github.io/vue2-timepicker/
what are they exactly? because my main interest now is int this functionality - being able to change value programmatically

**Comment by xxRockOnxx** [comment]
@shershen08 the original is very imperative and I refactored to behave more in vue's way.

Open an issue on my repo so I can point the PR on it. Will fix this in the morning.

**Comment by bazuzu931** [comment]
@xxRockOnxx thanks a lot buddy

**Comment by phoenixwong** [comment]
Duplicate of #27
