### ISSUE TITLE
Date in v-model

### ISSUE THREAD

**Issue by robertgon97** [phoenixwong/vue2-timepicker#45]
I need to make a v-model of a specific date like this: '2017-12-05T20: 00: 00.000Z' How can I solve my problem?

**Comment by xxRockOnxx** [comment]
I don't think this package is for that kind of purpose. This package is a "time" picker not a "date" picker.

**Comment by phoenixwong** [comment]
Sorry for the late reply.

Yes. @xxRockOnxx's reply is on point. There are other **date** picker (for dates only) and **datetime** picker (date + time) in the Vue community. While this repo is focusing on the "time"  parts only.
