### ISSUE TITLE
Add accessibilit features

### ISSUE THREAD

**Issue by TomFranssen** [phoenixwong/vue2-timepicker#49]
Is it possible to add accessibility features like tab navigation and opening the picker with the space and enter button?

This would greatly increase the ability to use this plugin.

**Comment by tornography** [comment]
Since this is a form element, not providing tab navigation is a no go. Looks good, but is unusable in pur context.
I wuld really appreciate the possibilty to use keyboard navigation.

**Comment by phoenixwong** [comment]
Welcome to take a peek at the nighty [v1.0.0-beta.2](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v1.0.0-beta.2) 🌱 version.

It's available in yarn/npm as well.

```
yarn add vue2-timepicker@beta
```

or

```
yarn upgrade vue2-timepicker@beta
```

Documentation for the 1.0.0-beta [goes here](https://github.com/phoenixwong/vue2-timepicker/blob/1-0-0/README.md).
