### ISSUE TITLE
How to disable lint when I'm developing...

### ISSUE THREAD

**Issue by zzz6519003** [phoenixwong/vue2-timepicker#5]
I wanna mess up the code a lot XD

**Comment by phoenixwong** [comment]
http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

**Comment by zzz6519003** [comment]
Is there another way instead of Disabling Rules with Inline Comments?
I think there should be a config set to do this.

Sorry for the helpless issue T.T
