### ISSUE TITLE
Bug in distribution version, uninitialized id-variable

### ISSUE THREAD

**Issue by oscarjlep** [phoenixwong/vue2-timepicker#51]
Hi,

I discovered a bug in dist/ .js version. Apparently there is a :id="id" binding, but the id-variable isn't initialized anywhere (and isn't used for that matter). It seems to me that you can simply remove :id="id" in order to get rid of Vue-errors.

**Comment by xxRockOnxx** [comment]
please check my fork. if it does not fix your problem, open an issue.

**Comment by phoenixwong** [comment]
Sorry for the long wait. Latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) fixes this issue now (#66)

**Comment by phoenixwong** [comment]
Duplicate of #10
