### ISSUE TITLE
babelrc

### ISSUE THREAD

**Issue by sbaudino** [phoenixwong/vue2-timepicker#52]
It will be great to change the .babelrc to this:

{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}

Thats because mostly all the vuejs projects have that config in the babelrc.

**Comment by xxRockOnxx** [comment]
please check my fork and see if this problem still persists. if it does, open an issue.

**Comment by sbaudino** [comment]
Yes. Check plz the file .babelrc. The original one just have:
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}

the idea is to change the content of this file to:
{
"presets": [
["env", { "modules": false }],
"stage-2"
],
"plugins": ["transform-runtime"],
"comments": false,
"env": {
"test": {
"presets": ["env", "stage-2"],
"plugins": [ "istanbul" ]
}
}
}

**Comment by Scegit** [comment]
The build used to fail with 

{
"presets": ["es2015", "stage-2"],
"plugins": ["transform-runtime"],
"comments": false
}

but when I tried 
{
"presets": [
["env", { "modules": false }],
"stage-2"
],
"plugins": ["transform-runtime"],
"comments": false,
"env": {
"test": {
"presets": ["env", "stage-2"],
"plugins": [ "istanbul" ]
}
}
}

It worked. it is just a timepicker and it shouldn't be complicated to install.

**Comment by phoenixwong** [comment]
Closing this with the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0). [#66]

**Comment by phoenixwong** [comment]
Related to #15
