### ISSUE TITLE
close on selection

### ISSUE THREAD

**Issue by sbaudino** [phoenixwong/vue2-timepicker#53]
Is it possible to close the picker div once I have selected hour and minutes? or when I have selected all.

**Comment by xxRockOnxx** [comment]
just add a listener? the clicks outside the picker to close it?

**Comment by sbaudino** [comment]
Yes, the idea is when the selection is complete (when I have selected hours, minutes and seconds or just hours and minutes) the picker div should close it like clicking outside the picker.

**Comment by zlydenkoa** [comment]
its a MUST have feature ._.

**Comment by phoenixwong** [comment]
Welcome to take a peek at the nighty [v1.0.0-beta.2](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v1.0.0-beta.2) 🌱 version.

It's available in yarn/npm as well.

```
yarn add vue2-timepicker@beta
```

or

```
yarn upgrade vue2-timepicker@beta
```

Documentation for the 1.0.0-beta [goes here](https://github.com/phoenixwong/vue2-timepicker/blob/1-0-0/README.md).
