### ISSUE TITLE
set placeholder

### ISSUE THREAD

**Issue by Chathula** [phoenixwong/vue2-timepicker#55]
Hello,

is there any way to set a placeholder instead of default`HH:mm:ss`. it is something very useful for UX.

Thank You...

**Comment by phoenixwong** [comment]
Sorry for the long wait! This feature has been released in [v0.2.1](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.1).

You can find samples in the [Documentation](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md) and [Demo](https://phoenixwong.github.io/vue2-timepicker/) page.
