### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by kperveen** [phoenixwong/vue2-timepicker#56]
I am using nuxt for my vue application but when I import time picker in my component it gives me this error
```
Unexpected token <
```

My current code to import date picker
```
import VueTimepicker from 'vue2-timepicker'
```

**Comment by xxRockOnxx** [comment]
Please check my fork and see if the problem still exists.

**Comment by jjanaks12** [comment]
i also find this error
![screenshot_1](https://user-images.githubusercontent.com/8529648/40303509-be7e693c-5d12-11e8-849d-c30458bee810.png)

**Comment by terryds** [comment]
@xxRockOnxx the problem still changes to 

render function or template not defined in component: anonymous

**Comment by xxRockOnxx** [comment]
@terryds did you install my fork?

**Comment by jjanaks12** [comment]
i solved this issue by turning of server rendering

**Comment by xxRockOnxx** [comment]
Oh, my bad, didn't notice thread is related to nuxt. didn't tested on nuxt yet. My fork is open for PRs if you managed to fix it.

**Comment by phoenixwong** [comment]
Sorry for the long wait. Please give the latest release [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) a try. [#66]

**Comment by kamilGawron** [comment]
Hello, I use 1.1.6 and still have a problem in Jest test:
![image](https://user-images.githubusercontent.com/30507634/114192850-3cb62180-994e-11eb-9ede-b9b1f28ef105.png)

Any solutions?
