### ISSUE TITLE
String HH:mm format in v-model

### ISSUE THREAD

**Issue by AnatolyArt** [phoenixwong/vue2-timepicker#58]
Hello can i get (and set) in v-model time like 21:34 , i don't want time object {hh:21, mm:34} it's hard to convert from/to server data

**Comment by daopapp** [comment]
Hi,
really, this format sucks.
But, I convert the object format before sending to the server.
Ex:
this.dataCreate.rules.begin_time = this.begin_time.HH + ':' + this.begin_time.mm

And for reading the time from the server and putting on object format:
Ex:
this.begin_time.HH = data.rules.begin_time.substring(0, 2)
        this.begin_time.mm = data.rules.begin_time.substring(3, 5)

I hope that this helps you

**Comment by usolved** [comment]
I just like to upvote this feature request. I'm also really looking forward to it if this would make it in one of the next releases :).

**Comment by phoenixwong** [comment]
Hi guys,

Welcome to take a peek at the :seedling: nighty [1.0.0-beta.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/1.0.0-beta.0) version.

It's available in yarn/npm as well.

```
yarn add vue2-timepicker@beta
```
or 
```
yarn upgrade vue2-timepicker@beta
```

FYI, a **[debug-mode](https://github.com/phoenixwong/vue2-timepicker/blob/1-0-0/README.md#enable-debug-mode)** helper is added to help to investigate the input -> output process.

Documentation for the **1.0.0-beta** [goes here](https://github.com/phoenixwong/vue2-timepicker/blob/1-0-0/README.md).

**Comment by usolved** [comment]
Thanks for implementing this feature :).
