### ISSUE TITLE
Change Style of Component

### ISSUE THREAD

**Issue by ConProgramming** [phoenixwong/vue2-timepicker#59]
Is there anyway to change the style of the component?

**Comment by xxRockOnxx** [comment]
you can add class to the component and then style that to override normal styles.

**Comment by ConProgramming** [comment]
@xxRockOnxx That doesn't work

**Comment by xxRockOnxx** [comment]
any code snippet on how you do it? Also can you open an issue here: https://github.com/xxRockOnxx/vue2-timepicker then reference this there?

**Comment by ConProgramming** [comment]
The html
```
                        <vue-timepicker 
                            class="timepicker" 
                            placeholder="End Time" 
                            name="time" 
                            :format="timePickerFormat" 
                            v-model="timePickerEndData"
                            hide-clear-button>
                        </vue-timepicker>
```

The style
```
    .timepicker {
        height: 30.8px;
        width: 201.48px;
        background-color: rgb(200, 18, 100);
    }
```

**Comment by ConProgramming** [comment]
@xxRockOnxx Why another issue?

**Comment by xxRockOnxx** [comment]
@ConProgramming this repo is dead. I made a fork a long time ago and trying to maintain it

**Comment by ConProgramming** [comment]
Ah. I might just use this instead, it appears built in https://uiv.wxsm.space/time-picker/

**Comment by nemanjazajk** [comment]
> Try this if you want to style input

> The style
> 
> ```
>     .timepicker  input[type="text"] {
>         height: 30.8px;
>         width: 201.48px;
>         background-color: rgb(200, 18, 100);
>     }
> ```

}
