### ISSUE TITLE
Question. Is it possible to set a hours range

### ISSUE THREAD

**Issue by zygisjas** [phoenixwong/vue2-timepicker#63]
Is it possible to set an available hours range, for example from 9 to 18 hours only?

**Comment by robertpro** [comment]
you can add two inputs, the first for the start time, and another one for the end time

**Comment by Themitchell** [comment]
as i understand it perhaps @zygisjas is referring to the same issue as this https://github.com/phoenixwong/vue2-timepicker/issues/65

**Comment by phoenixwong** [comment]
Sorry for the long wait. The latest version [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) [#66] release support for `hour-range` and `hide-disabled-hours`. Please give it a try.

If you want to set hours enabled from 9 to 18:

```html
<!-- 24-Hour Format -->
<vue-timepicker :hour-range="[[9, 18]]"></vue-timepicker>

<!-- 24-Hour Format + Hide Disabled Hour Ranges -->
<vue-timepicker :hour-range="[[9, 18]]" hide-disabled-hours></vue-timepicker>
```
