### ISSUE TITLE
Add Minute Range and Second Range Support

### ISSUE THREAD

**Issue by spham** [phoenixwong/vue2-timepicker#64]
Hi
i wish to show a calendar booking, so disable some hour or minute when user try to choose in timepicker, is it possible ?

**Comment by phoenixwong** [comment]
Sorry for the long wait. The latest version [v0.2.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.0) [#66] release support for `hour-range` and `hide-disabled-hours`. Please give it a try.

For minutes, I'm thinking you can try using the `minute-interval` property like `:minute-interval=15`

Samples can be found in the [README.md](https://github.com/phoenixwong/vue2-timepicker) and [Demo page](https://phoenixwong.github.io/vue2-timepicker/).

Duplicate of #63

**Comment by phoenixwong** [comment]
Reopen this for feature request - I'm considering adding support to minutes, seconds, apm range as per `hour-range`. Meanwhile, please feel free to make new PRs base on the [latest release](https://github.com/phoenixwong/vue2-timepicker/releases/latest) : )

**Comment by phoenixwong** [comment]
Included in pre-release [v1.0.0-beta.1](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v1.0.0-beta.1)
