### ISSUE TITLE
Module not found error in 0.2.0

### ISSUE THREAD

**Issue by RaphaelJ** [phoenixwong/vue2-timepicker#68]
It looks like I can't import vue2-timepicker in my Webpack project anymore:

```
ERROR in ./node_modules/vue2-timepicker/src/index.js
Module not found: Error: Can't resolve './vue-timepicker' in '[..]/node_modules/vue2-timepicker/src'
 @ ./node_modules/vue2-timepicker/src/index.js 1:0-44 2:15-28
```

However, changing the first line of `/src/index.js` to 

```
import VueTimepicker from './vue-timepicker.vue'
```

Fixes the issue.

Thank you for this very useful package.

**Comment by phoenixwong** [comment]
Thanks for the bug report. Fix released in [v0.2.1](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.1)
