### ISSUE TITLE
Provide ES Module

### ISSUE THREAD

**Issue by Trainmaster** [phoenixwong/vue2-timepicker#71]
Version: `0.2.2`

The following error is displayed when bundling with webpack@4. I think it's caused by excluding `node_modules` in `vue-loader` (which is a common thing).

```
[09:55:49] Error in plugin "webpack-stream"
Message:
    ./node_modules/vue2-timepicker/src/vue-timepicker.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <script>
| const CONFIG = {
|   HOUR_TOKENS: ['HH', 'H', 'hh', 'h', 'kk', 'k'],
```

Nevertheless it should work. According to https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-does-npm-know-which-version-to-serve-to-a-browser-build-process a ESM build must be provided:

> When webpack 2+, Rollup, or other modern build tools are used, they will pick up on the module build.

**Comment by phoenixwong** [comment]
Thanks for the bug report!

A pre-release [v0.2.2-rc.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.2-rc.0) is added (available in npm as well). Please give it a try and let me know if it resolves the problem you met.
