### ISSUE TITLE
AM / PM is not updating 

### ISSUE THREAD

**Issue by OneParishLukas** [phoenixwong/vue2-timepicker#72]
I am using the timepicker and I noticed that the AM/PM is not updating properly when I select the picker.

This is how I initialize the time:
`const now = new Date();
            const time = {};
            time.HH = now.getHours();
            time.mm = now.getMinutes();
            time.A = (time.HH >= 12) ? "PM" : "AM";`

then in data
`sendLaterTime: time,`

then in template(I am using PUG)
`vue-timepicker(
                    format='HH:mm A'
                    v-model="sendLaterTime"
                    :minute-interval="10")`

I see hours and minutes updating properly, but not the A property. Any ideas?

**Comment by phoenixwong** [comment]
Hi there, I built a JSFiddle base on your codes here: [Vue2 Timepicker AM PM Demo](https://jsfiddle.net/phoenixwong/fpa367xs/). Both HH/mm/A are working fine.

If you still seeing any issue on your end, please fork the above demo and try reproducing it with the Fiddle. Thanks!

**Comment by OneParishLukas** [comment]
Hi! Sorry I realized my issue and fixed it. Thanks again!
