### ISSUE TITLE
Css not loading

### ISSUE THREAD

**Issue by ruanltbg** [phoenixwong/vue2-timepicker#73]
Hi based on the doc this should import and use the css
```
// Import the *.vue file (CSS included)
import VueTimepicker from 'vue2-timepicker'
```
A tried that and on my project, this is not working.

On version `vue2-timepicker@^0.2.2` I get this error:
```
ERROR in ./node_modules/vue2-timepicker/src/vue-timepicker.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue2-timepicker/src/vue-timepicker.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
    at validate (/Users/ruakov/workspace/private/script-tool/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/ruakov/workspace/private/script-tool/node_modules/css-loader/dist/index.js:34:28)
```

On the version `0.2.2-rc.0` I do not get css at all. 

Could you take a look and help me with that? 

At the moment I am using `0.2.2-rc.0` and importing `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vue2-timepicker@0.2.2/dist/VueTimepicker.css">` manually. 

Cordially

ref: #34

**Comment by phoenixwong** [comment]
Related to #71 

Users who met bundle/loader issues with `v0.2.2` or any previous versions, please try [v0.2.2-rc.0](https://github.com/phoenixwong/vue2-timepicker/releases/tag/v0.2.2-rc.0) along with the [updated documentation here](https://github.com/phoenixwong/vue2-timepicker/blob/alpha/README.md#get-started) (in the pre-release branch) and use the latest import methods.

**Comment by phoenixwong** [comment]
Thanks for the follow-up, @ruanltbg!

As @Trainmaster mentioned in #71, the loaders (either vue-loader, vue-style-loader, or css-loader) intend to exclude files from `node_modules` by default, unless you add some workarounds in the bundler's config base on your circumstances.

I'm glad you found the solution in your case. I'll adjust the documentation as well in the upcoming release.
