### ISSUE TITLE
matchAll not supported by Edge, IE11 and Safari

### ISSUE THREAD

**Issue by usolved** [phoenixwong/vue2-timepicker#76]
Thanks for the latest release. There are really cool and handy improvements to it :).
I just noticed that Microsoft Edge, IE11 and Safari (the latter not tested) don't have support for "matchAll":

`"TypeError: Object doesn't support property or method 'matchAll'"`

In the function readStringValues there are the following calls to parse predefined or loaded values:

`  s = n.matchAll(new RegExp(i, "g")), u = n.matchAll(new RegExp(o, "g"))`

Babel is currently not able to compile it for compatibility reasons. I don't know if the scope if this project is to provide compatibility for these browsers but I would be happy if it would :).

**Comment by phoenixwong** [comment]
Hmm... so, according to the [MDN docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#Browser_compatibility), Windows Edge and Safari are still not supporting the `matchAll` method at this moment. 🤔

I'll try to add some polyfills for these browsers. Thanks for the report!

**Comment by phoenixwong** [comment]
Polyfill for Edge and Safari added in `v1.0.1`. Please give it a try.

No plan for supporting IE. Wish it luck! ☮️

**Comment by usolved** [comment]
Thank you so much! :)
It even works in IE now.

It really is not a matter of course and i am really thankful for the implementation.
