### ISSUE TITLE
How to style input with css?

### ISSUE THREAD

**Issue by fuoridallarete** [phoenixwong/vue2-timepicker#77]
Hi, thanks for your component. Super simple to use and does its job! 
The issue is not a big deal, but still. 
I can't manage to **add style to the input**. 
If I add a class to the component it get overridden by the input style. I can do it in the browser but then in my code I can't figure out how to target it.
`.vue__time-picker input.display-time` (as seen in the elements inspection) doesn't work, as well as just `input.display-time` or just `.display-time`.
Can you please help? 
Thanks a lot

**Comment by phoenixwong** [comment]
You can either add `!important` to force apply any CSS properties or use a higher priority CSS selector for the target `<input />`.

I made a quick example of the `inputClass` usage, please refer to the [JSFiddle here](https://jsfiddle.net/phoenixwong/y9sjo3cu/)

**Comment by fuoridallarete** [comment]
I can in your jsFiddle it works, but not for me :(

**Comment by fuoridallarete** [comment]
I can see in your jsFiddle it's working, but not for me. :( 
I also tried inline style but nothing. 
I was thinking to just delete the import of the css and copy it raw from your repo. But coping just VueTimepicker.css doesn't apply the style to the drop-down selection (also the x button stays out). What do you think about this solution? What files are included in the css import? So which ones I need to manually copy to get the basic style and then be able to add my own?
Thanks again for your patience :)

**Comment by fuoridallarete** [comment]
I sorted it out, I keep both. Your import and my css file with the css copied from VueTimepicker.css. If I change this file it works! Thanks and well done again.  :)

**Comment by VelenAranha** [comment]
Is there a way to pass inline styles to input ?

**Comment by phoenixwong** [comment]
Nope, inline styles for the `<input>` element is not supported. We recommend adding class name(s) to the `<input>` box through the `input-class` property ([docs here](https://github.com/phoenixwong/vue2-timepicker#the-input-class),  _v0.2.1+_), and write your own CSS styles for the defined class.

P.S. Several [CSS helper class names](https://github.com/phoenixwong/vue2-timepicker#helper-css-class-names) are introduced since _v1.1.0_, please give them a try.
