### ISSUE TITLE
Auto-Scrolling to the selected time doesn't work with an initial value

### ISSUE THREAD

**Issue by usolved** [phoenixwong/vue2-timepicker#79]
I'm using the latest release and I just noticed that the drop down to select hour/minute doesn't scroll/jump to the pre defined initial value when clicking on the field to change the time.

**Example:**
I set 13:45 as initial value (it doesn't matter if I'm using string or object). When I click on the field to change the value the time is selected correctly but the view doesn't move to the right spot and the scrollbar stays on top.

If I again select 13 (or any other hour), close the selector and reopen it again then the scrollbar has stayed on the right position.

**Comment by phoenixwong** [comment]
Actually, we don't have any auto-scroll feature implemented in the component. That seemingly auto-scroll you witnessed was trigger by the browser itself.

We can mark it as an enhancement in a later phase, though.
