### ISSUE TITLE
Optional parameter to allow manual input

### ISSUE THREAD

**Issue by usolved** [phoenixwong/vue2-timepicker#80]
To allow manual input of the time (like in a default input text field) without the drop down it would be cool to have an optional parameter to turn that feature on/off.

I think users that are using a form more often (or tech savvy users) would appreciate such a function to fill out the form faster.

With manual input there could be invalid inputs. So that's a downside but either you check the format only on the backend or this plugin would also add an integrated validation for manual input depending on the configured time format to automatically correct invalid inputs.

**Comment by yujin1st** [comment]
+1

**Comment by Elite40** [comment]
+1

**Comment by SylverFox** [comment]
+1

**Comment by andreixk** [comment]
+1

**Comment by usolved** [comment]
Thanks a lot for all the work you've put into this feature.
Can't wait to try out release 1.1.0 :).
