### ISSUE TITLE
Default close not working in bootstrap modal

### ISSUE THREAD

**Issue by game09488** [phoenixwong/vue2-timepicker#82]
When the timepicker is inside a modal, I cannot close the timepicker by clicking the modal. Any way to counter this?

**Comment by ericcch** [comment]
Hi game09488,

Are you using gridform by any chance? 

if you're, then the gridform js might be causing the problem. Just exclude .display-time class from the focusableFields jquery selector

**Comment by phoenixwong** [comment]
Hi @game09488,

Can you try the solution mentioned by @ericcch and see if it resolves the problem on your end?

If the issue still exists, please provide us a minimum reproduction of your issue on JSFiddle, CodePen, or your domain. The current information you give is insufficient.

**Comment by game09488** [comment]
Yup, it does fix my issue. Sorry for late reply
