### ISSUE TITLE
默认值怎么修改呢？

### ISSUE THREAD

**Issue by lmw0221** [phoenixwong/vue2-timepicker#88]
比如 00:mm的情况

**Comment by phoenixwong** [comment]
It's all in the documentation. Please check the [Data Binding section here](https://github.com/phoenixwong/vue2-timepicker/blob/master/README.md#data-binding).

P.S. To help other people - not only me but also other latecomers who might raise the same question as you did - understand your question, I'd suggest you use English when commenting or opening a new issue. Thanks!
