### ISSUE TITLE
'mm' format rendering as 'm'

### ISSUE THREAD

**Issue by ksherman** [phoenixwong/vue2-timepicker#9]
Hi there! Really like your component! I'm having a problem with the time formatting that is rendered out.

I'm looping through and splitting a date object over to the correct format for your v-model setup. And any of the minute strings less than 10 that should have tow digits (e.g. `3` should be `03`) is being rendered out as just the single digit. I'm probably missing something. 

This is what one of my components' data looks like in VueDevtools:
```
passedValue: "1970-01-01 00:05:00" prop
yourData: Object
   a: "am"
   h: "12"
   mm: "05"
```

and then it renders out on the page like:
`Start Time:  12:5 am`

```
<template>
	<vue-timepicker format="h:mm a" :minute-interval="5" v-model="yourData"></vue-timepicker>
</template>

<script>
	import VueTimepicker from 'vue2-timepicker';
	export default {
		components: {
			VueTimepicker
		},
		props: [
			'passedValue'
		],
		data() {
			return {
				yourData: {
					h: '',
					mm: '',
					a: ''
				}
			}
		},
		created() {
			this.splitObject(this.passedValue);
		},
		methods: {
			splitObject(date) {
				var date = new Date(date);
				this.yourData.h = date.getHours() % 12 || 12;
				this.yourData.h = this.yourData.h.toString();
				this.yourData.a = date.getHours() >= 12 ? 'pm' : 'am';
				this.yourData.mm = date.getMinutes().toString();
			}

		}
	};
</script>
```

Any help is appreciated! 

Also, and I'm sure this falls into easier-said-than-done territory, but it would be sweet to be able to "just" pass in a javascript Date Object instead of needing to split for h/m/s etc.

**Comment by phoenixwong** [comment]
Hi @ksherman ,

You just need to change one of your code lines:

```javascript
// Before
// `mm` was recieving '5' rather than the expected '05'
this.yourData.mm = date.getMinutes().toString();
```

```javascript
// After
this.yourData.mm = (date.getMinutes() < 10 ? '0' : '') + date.getMinutes()
```

And thank you for the Date Object suggestion. I actually thought about it at the very beginning of creating this repo. However, after some pondering, I prefer to keep `vue-timepicker` as a light-weight UI component for a while.

Plus, there're many professional date-time parsing libraries. I recommend [MomentJS](http://momentjs.com/) the most.

Here's a rough demo of how MomentJS could work with your data parsing. Hope it helps!
https://jsfiddle.net/phoenixwong/zvkmc760/

**Comment by ksherman** [comment]
Thanks! That did fix the issue. 

I've thought about using MomentJS, seems like a really useful library. I think as I start requiring more time-related components, I'll probably end up using it. Trying to avoid a whole library for just a few utilities :-D

Thanks again!
