### ISSUE TITLE
Trigger open from outside

### ISSUE THREAD

**Issue by six7** [phoenixwong/vue2-timepicker#92]
Would be great if the time picker allowed to be opened from outside - e.g. a button next to the time picker input. Just went through the code and couldn't find any such reference.

One possible implementation could be passing a prop "isOpen" for example.

**Comment by phoenixwong** [comment]
You can do that with the help of Vue's **[$refs](https://vuejs.org/v2/api/#ref)**.

Here's a [workable sample in JSFiddle](https://jsfiddle.net/phoenixwong/p8xmkd40/).
