### ISSUE TITLE
Vue-Bootstrap related: mouse drag on the scrollbar handler lead to a dropdown close instantly

### ISSUE THREAD

**Issue by kapdom** [phoenixwong/vue2-timepicker#94]
Hi. When I use scroll bar to select hour or minute to choose, selector instantly close. Using mouse scroll wheel everything is fine.

I noticed that problem appears only when time picker is in <b-modal> component from  vue-bootstrap. 
Any idea how to fix it?
 
Regards

**Comment by phoenixwong** [comment]
Hi @kapdom,

Can you provide a minimal demo of the `vue-bootstrap` + `vue-timepicker` issue you met with JSFiddle or CodePen? Great thanks!

**Comment by kapdom** [comment]
How can I add vue-timepicker to JSFiddle? Is there any cdnjs link for your plugin?
Regards

**Comment by phoenixwong** [comment]
Please try forking this JSFiddle: https://jsfiddle.net/phoenixwong/hyndu409/

The `vue2-timepicker@v1.0.4` is already included in the Resources.

**Comment by kapdom** [comment]
Try now. https://jsfiddle.net/er8ymas4/

**Comment by phoenixwong** [comment]
Thanks for the Demo!

To recap, by saying "_use scroll bar to select hour or minute to choose_", you meant drag-to-scroll the hour/minute list with the scroll handlers (red-circled targets in the screenshot below), correct?

<img width="578" alt="Vue2Timepicker-in-bModal" src="https://user-images.githubusercontent.com/6954306/70332863-6607fe80-187d-11ea-98b7-b89e937aed64.png">

**Comment by phoenixwong** [comment]
At a quick glance, when you drag the scrollbar handler with a mouse, the VueBootstrap Modal may think you are leaving the modal and try to focus back to its modal body. Which causes a `blur` event on vue-timepicker and leads to the dropdown close.

From their [current documentation](https://bootstrap-vue.js.org/docs/components/modal), I can’t find a property to disabled this `<b-modal>` feature. I need to dig into the VueBoostrap source code for more details.

For now, the quickest workaround is to set a relatively large value for `blur-delay` on **vue-timepicker**

```
<vue-timepicker :blur-delay="1200"></vue-timepicker>
```

**Comment by kapdom** [comment]
Thx. Your trick with blur-delay fixed a problem a bit. Another problem that I spotted just now is when you turn on option "close-on-complete". It close window immediately after click first value but it should close when all values are selected.

Thank you one more time for your help. Your time picker is the best  :). I couldn't find anything better.

Regards

**Comment by phoenixwong** [comment]
Thanks for your support as well :)

BTW, did you found the `close-on-complete` issue by putting the **vue-timepicker** in one of the Vue-Bootstrap, either? I cannot reproduce it with your `<b-modal>` demo (https://jsfiddle.net/er8ymas4/)

```
<b-modal id="modal-1" title="BootstrapVue">
  <vue-timepicker close-on-complete></vue-timepicker>
</b-modal>
```

![close-on-complete-w-bModal](https://user-images.githubusercontent.com/6954306/70386875-1fc7b200-19d9-11ea-9e90-19733ecd1544.gif)

**Comment by kapdom** [comment]
It's weird, but now problem with closing window after first value selected gone.
Sorry for this.
Regards.

**Comment by Ruinevo** [comment]
Hello. I confirm this problem. 

I get the same bug without using bootstrap or any library.

You may try this even on the demo page. https://phoenixwong.github.io/vue2-timepicker/

**Comment by TitoAgudelo** [comment]
@phoenixwong I was trying to fix the issue principally because first I have seated my time by default time so when I use "close-on-complete" my time is completed and still having same issue but with your release everything works perfectly thanks
