### ISSUE TITLE
npm run watch error

### ISSUE THREAD

**Issue by ayophanz** [phoenixwong/vue2-timepicker#95]
after installing I've got error, I tried to uninstall but the issue remain because of this package.

![image](https://user-images.githubusercontent.com/24581584/70044619-ac4f2a80-15fd-11ea-806a-da6fd8426e19.png)

**Comment by phoenixwong** [comment]
Hmm... I guess you should post the bug in [vue2-daterange-picker](https://github.com/Innologica/vue2-daterange-picker) instead. So far as I know, `vue2-timepicker` is not in the dependencies list of `vue2-daterange-picker`.

**Comment by ayophanz** [comment]
Its ok now
